### ISSUE TITLE
how do handle json request/response objects

### ISSUE THREAD

**Issue by evnix** [pmjones/AutoRoute#7]
This is from a basic standard spring http controller example,

```java
public ResponseEntity<Car> update(@RequestBody Car car) {

    if (car != null) {
        car.setMiles(car.getMiles() + 100);
    }

    // TODO: call persistence/service layer to update
    return new ResponseEntity<Car>(car, HttpStatus.OK);
}
```

how do i do this without having to manually call json encode and decode conversions?

**Comment by pmjones** [comment]
I don't see how this is a routing question ... ?

**Comment by solidpulse** [comment]
probably he meant, because if the following is possible
```php
invoke(int $companyId)
```

then why not this,

```php
invoke(Company $company)
```
But @ evnix just because this is common/standard practise in Java and NodeJS world doesn't mean we have to follow suite.

as @pmjones mentioned, AutoRoute is limited to handling GET URL params, we don't really care about POST params, AutoRoute as the name suggests is only for routing and is cutting edge and not just another routing framework. 

AutoRoute is like the kernel, the real deep core level stuff. It is up to you to build what you want on top of it.

if you want to do the old request/response stuff, stick to something like https://github.com/thephpleague/route
